#!/bin/bash
#

[ "$1" != "" ] && OUT=$1

if [ $(whoami) != root ]; then
	echo "Run me as root or under sudo"
	exit 1
fi

do_run()
{
	size=$1; shift
	mode=$*
	echo ###############
	echo $size $mode
	/usr/bin/time $TOOLDIR/iodme-file-write $size $mode $OUT
	echo ###############
}

[ "$TOOLDIR" = "" ] && TOOLDIR=tools 

SIZES="1GB 2GB"

# Increase pipe buffer size to 4MB (default is 1MB)
# This helps reduce number of vmsplice() calls
echo 4194304 > /proc/sys/fs/pipe-max-size

# Drop all caches
echo 3 > /proc/sys/vm/drop_caches

# Make sure we have enough huge pages
# To accomodate 1GB and 2GB mappings
echo 2024 > /proc/sys/vm/nr_hugepages
echo 2024 > /proc/sys/vm/nr_hugepages

for s in $SIZES; do
	do_run $s
	do_run $s use_directio
	do_run $s use_hugepages
	do_run $s use_directio use_hugepages
	do_run $s use_splice
	do_run $s use_splice use_hugepages
	do_run $s use_splice use_directio
	do_run $s use_splice use_directio use_hugepages
	do_run $s use_memfd
	do_run $s use_memfd use_hugepages
	do_run $s use_memfd use_directio
	do_run $s use_memfd use_directio use_hugepages
done
